apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rhopp-go-azure 
  janus-idp.io/tekton: rhopp-go-azure
  backstage.io/kubernetes-id: rhopp-go-azure
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rhopp-go-azure
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml