apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhopp-go-azure
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhopp-go-azure 
  name: rhopp-go-azure
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rhopp-go-azure 
